site_name: Panel Chat Examples
site_description: Example recipes for Panel Chat Components

repo_url: https://github.com/holoviz-topics/panel-chat-examples
repo_name: holoviz-topics/panel-chat-examples

theme:
    name: material
    logo: 'assets/images/panel-logo.png'
    features:
        - content.copy.code
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: blue
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: blue
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.9/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - panel_chat_examples

nav:
    - Home: index.md
    - Basics: basics.md
    - Components: components.md
    - Features: features.md
    - Langchain: langchain.md
    - Mistral: mistral.md
    - OpenAI: openai.md
