name: Build

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.9']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
        hatch env create
    - name: Lint and typecheck
      run: |
        hatch run lint-check
    - name: Install Playwright browser(s)
      run: |
        hatch run playwright install chromium
    - name: Test
      run: |
        hatch run test-cov-xml
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
