name: Run Tests

env:
  # enable colored output
  # https://github.com/pytest-dev/pytest/issues/7443
  PY_COLORS: 1

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_tests:
    name: ${{ matrix.test-type == '' && 'all' || matrix.test-type }} (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    timeout-minutes: 15
    strategy:
      matrix:
        # run no_llm tests across all python versions and oses
        os: [ubuntu-latest]
        python-version: ['3.10']
        test-type: ''
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install requirements
        run: pip install ".[all]"

      - name: Run tests
        run: pytest -n auto -vv
        if: ${{ !(github.event.pull_request.head.repo.fork) && matrix.test-type == '' }}
